# Generated by Django 2.2.28 on 2023-04-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samz', '0002_buyer_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
